name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  create_image:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/docker-root-image:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: give execution permition
        run: |
          ls
          pwd #chmod +x plugin/entrypoint.sh
      - name: Run build script
        run: /plugin/entrypoint.sh
        shell: bash

