name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  create_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - name: Docker login
        run: echo ${{ secrets.github_token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: show password
        run: cat /home/runner/.docker/config.json
      - name: Build image
        run: |
          ls -la
