name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  create_image:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/docker-root-image:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: Docker login
        run : |
          pwd
          ls 
          test.sh
#        run: echo ${{ secrets.github_token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#      - name: Build image
#        run: |
#          docker build -t ghcr.io/$GITHUB_REPOSITORY .
#      - name: Push image 
#        run: |
#          docker push ghcr.io/$GITHUB_REPOSITORY
